version: '3.2'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  # mongo:
  #   image: mongo
  #   container_name: app_mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ~/mongo:/data/db

volumes:
  postgres:
  # mongo:
